language: node_js
node_js:
- '8'
addons:
  firefox: latest
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
jobs:
  include:
    - stage: lint
    - script: npm run lint
    - stage: build-and-test
    - script:
      - npm run build
      - npm run test
