language: node_js
node_js:
- '8'
addons:
  firefox: latest
sudo: false
before_install:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
script:
  - npm run lint
  - npm run build
  - npm run test
